kind: "CronJob"
apiVersion: "batch/v1beta1"
metadata:
  name: "cron.reporting.massopen.local"
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 290
      template:
        metadata:
          name: "runner.cron.reporting.massopen.local"
        spec:
          containers:
          - name: "moc-reporting-runner"
            image: "172.30.1.1:5000/myproject/moc_reporting_testing:latest"
            volumeMounts:
              - name: "moc-creds"
                mountPath: "/moc-creds"
                readOnly: true
              - name: "reporting-db"
                mountPath: "/usr/local/pgsql/data"
                readOnly: false
          volumes:
            - name: "moc-creds"
              secret:
                secretName: "moc-creds"
            - name: "reporting-db"
              persistentVolumeClaim:
                claimName: "moc-reporting-db"
          restartPolicy: "Never"
